/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

function Table(props) {
  const { nodes, materials } = useGLTF('/assets/models/Office.gltf');
  return (
    <group {...props} dispose={null}>
      <group position={[29.53, -89.68, 14.33]} rotation={[0, 1.57, 0]} scale={12.3}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Bld_Ceiling_Panel_02.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[1.15, 8.92, -2.37]}
          rotation={[0, -1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Bld_Ceiling_Panel_02_(1)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[1.15, 8.92, 0.11]}
          rotation={[0, -1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Bld_Ceiling_Panel_02_(2)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-1.35, 8.92, -2.37]}
          rotation={[0, -1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Bld_Ceiling_Panel_02_(3)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-1.35, 8.92, 0.11]}
          rotation={[0, -1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Bld_Door_04.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[0.4, 5.93, -4.93]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Bld_Floor_Carpet_01_(79)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[1.15, 5.93, -4.87]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Bld_Floor_Carpet_01_(80)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[1.16, 5.93, -4.87]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Bld_Floor_Carpet_01_(82)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[1.15, 5.93, -2.37]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Bld_Floor_Carpet_01_(83)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[1.16, 5.93, -2.37]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Bld_Wall_Baseboard_01_(114)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-1.34, 5.93, 0.13]}
          rotation={[0, -1.57, 0]}
          scale={[2, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Bld_Wall_Baseboard_01_(12)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[3.65, 5.93, -4.87]}
          rotation={[0, 1.57, 0]}
          scale={[2, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Bld_Wall_Baseboard_Door_01_(22)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-1.34, 5.93, -4.87]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <group position={[3.65, 5.93, 0.13]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_5.geometry} material={materials.PolygonOffice_Material_02_A} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_5_1.geometry} material={materials.PolygonOffice_Material_Glass} />
        </group>
        <group position={[1.16, 5.93, 0.13]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_6.geometry} material={materials.PolygonOffice_Material_02_A} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_6_1.geometry} material={materials.PolygonOffice_Material_Glass} />
        </group>
        <group position={[1.15, 5.93, -4.87]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_7.geometry} material={materials.PolygonOffice_Material_02_A} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_7_1.geometry} material={materials.PolygonOffice_Material_Glass} />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Bld_Wall_Window_Blinds_Closed_01.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[1.16, 5.93, 0.13]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Bld_Wall_Window_Blinds_Open_04_(1)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[1.15, 5.93, -4.87]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Bld_Wall_Window_Blinds_Up_01.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[3.65, 5.93, 0.13]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_Alcohol_Bottle_01.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[1.18, 6.67, -1.93]}
          rotation={[0, -0.63, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Prop_Book_Group_01_(2)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-0.93, 7.15, -0.97]}
          rotation={[0, -1.57, 0]}
          scale={0.9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Prop_Book_Group_02_(3)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-0.95, 6.86, -1.32]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.81}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Prop_Book_Group_03_(3)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-0.93, 6.56, -1]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.83}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Prop_Book_Group_04_(4)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-0.96, 7.15, -1.5]}
          rotation={[0, 1.36, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_Book_Group_08.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-0.86, 6.86, -0.74]}
          rotation={[0, -1.3, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_Card_Scanner_01.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-0.8, 6.98, -5.01]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_CardRoller_01.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[1.13, 6.68, -3.39]}
          rotation={[Math.PI, -1.23, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Prop_Cellphone_01_(3)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[1.53, 6.67, -1.92]}
          rotation={[0, -0.37, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Prop_Certificate_01_(2)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[1.19, 7.51, 0.01]}
        />
        <mesh
          onClick={() => console.log('silla derecha')}
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_Chair_01.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-0.12, 5.93, -3.22]}
          rotation={[-Math.PI, -0.97, -Math.PI]}
        />
        <mesh
          onClick={() => console.log('silla izquierda')}
          castShadow
          receiveShadow
          geometry={nodes['SM_Prop_Chair_01_(1)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-0.01, 5.93, -2.17]}
          rotation={[0, -1.19, 0]}
        />
        <mesh
          onClick={() => console.log('Silla terciopelo')}
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_Chair_08.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[2.32, 5.91, -2.81]}
          rotation={[0, 1.26, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Prop_Clock_01_(6)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[1.01, 8.16, -4.73]}
          rotation={[-Math.PI, 0, -Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Prop_Clock_01_Hand_01.geometry}
            material={materials.PolygonOffice_Material_02_A}
            position={[0, 0, -0.04]}
            rotation={[0, 0, 2.19]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Prop_Clock_01_Hand_02.geometry}
            material={materials.PolygonOffice_Material_02_A}
            position={[0, 0, -0.04]}
            rotation={[0.09, -0.03, -0.81]}
          />
        </mesh>
        <group onClick={() => console.log('Esto es la pantalla')} position={[1.31, 6.68, -2.28]} rotation={[0, -0.99, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_26.geometry} material={materials.PolygonOffice_Material_02_A} />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh_26_1.geometry}
            material={materials.PolygonOffice_Material_Screen_05}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_Console_MegaCube_01.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-0.91, 6.56, -1.58]}
          rotation={[0, -1.57, 0]}
        />
        <mesh
          onClick={() => console.log('Esto es el mando de xbox')}
          castShadow
          receiveShadow
          geometry={nodes['SM_Prop_Controller_01_(2)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-0.91, 7.15, -0.85]}
          rotation={[0, -1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_Darkboard_01.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[3.51, 7.63, -0.55]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_Desk_03.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[1.25, 5.93, -2.81]}
          rotation={[0, -1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_Employee_Wall_01.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-1.14, 8.06, -3.33]}
          rotation={[0, -1.57, 0]}
        />
        <group
          onClick={() => console.log('Esto es el ordenador')}
          position={[1.38, 6.68, -2.92]}
          rotation={[Math.PI, -1.51, Math.PI]}
        >
          <mesh castShadow receiveShadow geometry={nodes.mesh_32.geometry} material={materials.PolygonOffice_Material_02_A} />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh_32_1.geometry}
            material={materials.PolygonOffice_Material_Screen_03}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_Minigolf_Ball_01.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[0.91, 6, -0.62]}
        />
        <mesh
          onClick={() => console.log('Esto es el palo del minigolf')}
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_Minigolf_Club_01.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[0.16, 6.63, -0.08]}
          rotation={[0.18, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_Minigolf_Flag_01.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[2.9, 5.93, -0.62]}
          rotation={[0, 0.95, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_Minigolf_Green_01.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[0.65, 5.93, -0.62]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Prop_Phone_Desk_01_(1)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[1.58, 6.68, -3.53]}
          rotation={[-Math.PI, -0.98, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Prop_Presentation_Chart_01_(1)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[2.71, 5.93, -4.05]}
          rotation={[-Math.PI, 0.94, -Math.PI]}
        />
        <group
          onClick={() => console.log('Esto es la las graficas de detras del escritorio')}
          position={[3.53, 8.75, -2.43]}
          rotation={[0, 1.57, 0]}
        >
          <mesh castShadow receiveShadow geometry={nodes.mesh_39.geometry} material={materials.PolygonOffice_Material_02_A} />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh_39_1.geometry}
            material={materials.PolygonOffice_Material_Screen_02}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_Shelf_05.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-0.96, 5.93, -1.14]}
          rotation={[0, -1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_Spaceship_01.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[0.99, 6.67, -1.93]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_Prop_Trophy_01.geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-0.96, 7.44, -0.59]}
          rotation={[0, -1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Prop_WallDressing_02_(4)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[1.13, 7.02, -4.72]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SM_Prop_WallDressing_03_(3)'].geometry}
          material={materials.PolygonOffice_Material_02_A}
          position={[-1.21, 7.5, -1.18]}
          rotation={[0, -Math.PI / 2, 0]}
        />
      </group>
    </group>
  );
}

export default Table;
